application: udatheme
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
- url: /
  script: main.app
- url: /signup
  script: usr.app
- url: /login
  script: usr.app
- url: /welcome
  script: usr.app
- url: /blog.*
  script: blog.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
